// Auto-generated by LibreLane
module systolic_array(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input enable,
  input clear_acc,
  input load_weights,
  input compute_enable,
  input[31:0] a_inputs_flat,
  input[31:0] b_inputs_flat,
  output[63:0] results_flat,
  output ready
);
endmodule
