/* Blackbox stub generated by make_stub.py */

module activation (
	clk,
	reset,
	enable,
	core_state,
	activation_enable,
	activation_func,
	unbiased_activation,
	bias,
	activation_out
);
endmodule

module alu (
	clk,
	reset,
	enable,
	core_state,
	decoded_alu_arithmetic_mux,
	decoded_alu_output_mux,
	rs,
	rt,
	alu_out
);
endmodule

module branch_diverge (
	clk,
	reset,
	enable,
	branch_instruction,
	branch_taken,
	branch_target,
	fallthrough_pc,
	reconverge_pc,
	current_pc,
	active_mask,
	next_pc,
	diverged,
	stall
);
endmodule

module cache (
	clk,
	reset,
	read_valid,
	read_address,
	read_ready,
	read_data,
	mem_read_valid,
	mem_read_address,
	mem_read_ready,
	mem_read_data
);
endmodule

module controller (
	clk,
	reset,
	consumer_read_valid,
	consumer_read_address_flat,
	consumer_read_ready,
	consumer_read_data_flat,
	consumer_write_valid,
	consumer_write_address_flat,
	consumer_write_data_flat,
	consumer_write_ready,
	mem_read_valid,
	mem_read_address_flat,
	mem_read_ready,
	mem_read_data_flat,
	mem_write_valid,
	mem_write_address_flat,
	mem_write_data_flat,
	mem_write_ready
);
endmodule

module core (
	clk,
	reset,
	start,
	done,
	block_id,
	thread_count,
	core_state_for_decode,
	instruction_for_decode,
	decoded_rd_address,
	decoded_rs_address,
	decoded_rt_address,
	decoded_nzp,
	decoded_immediate,
	decoded_reg_write_enable,
	decoded_mem_read_enable,
	decoded_mem_write_enable,
	decoded_nzp_write_enable,
	decoded_reg_input_mux,
	decoded_alu_arithmetic_mux,
	decoded_alu_output_mux,
	decoded_pc_mux,
	decoded_fma_enable,
	decoded_act_enable,
	decoded_act_func,
	decoded_systolic_enable,
	decoded_systolic_op,
	decoded_systolic_idx,
	decoded_branch,
	decoded_ret,
	program_mem_read_valid,
	program_mem_read_address,
	program_mem_read_ready,
	program_mem_read_data,
	data_mem_read_valid,
	data_mem_read_address_flat,
	data_mem_read_ready,
	data_mem_read_data_flat,
	data_mem_write_valid,
	data_mem_write_address_flat,
	data_mem_write_data_flat,
	data_mem_write_ready
);
endmodule

module dcr (
	clk,
	reset,
	device_control_write_enable,
	device_control_data,
	thread_count
);
endmodule

module decoder (
	clk,
	reset,
	core_state,
	instruction,
	decoded_rd_address,
	decoded_rs_address,
	decoded_rt_address,
	decoded_nzp,
	decoded_immediate,
	decoded_reg_write_enable,
	decoded_mem_read_enable,
	decoded_mem_write_enable,
	decoded_nzp_write_enable,
	decoded_reg_input_mux,
	decoded_alu_arithmetic_mux,
	decoded_alu_output_mux,
	decoded_pc_mux,
	decoded_fma_enable,
	decoded_act_enable,
	decoded_act_func,
	decoded_systolic_enable,
	decoded_systolic_op,
	decoded_systolic_idx,
	decoded_branch,
	decoded_ret
);
endmodule

module dispatch (
	clk,
	reset,
	start,
	thread_count,
	core_done,
	core_start,
	core_reset,
	core_block_id_flat,
	core_thread_count_flat,
	done
);
endmodule

module fetcher (
	clk,
	reset,
	core_state,
	current_pc,
	mem_read_valid,
	mem_read_address,
	mem_read_ready,
	mem_read_data,
	fetcher_state,
	instruction
);
endmodule

module fma (
	clk,
	reset,
	enable,
	core_state,
	decoded_fma_enable,
	rs,
	rt,
	rq,
	fma_out
);
endmodule

module gpu (
	clk,
	reset,
	start,
	done,
	device_control_write_enable,
	device_control_data,
	program_mem_read_valid,
	program_mem_read_address_flat,
	program_mem_read_ready,
	program_mem_read_data_flat,
	data_mem_read_valid,
	data_mem_read_address_flat,
	data_mem_read_ready,
	data_mem_read_data_flat,
	data_mem_write_valid,
	data_mem_write_address_flat,
	data_mem_write_data_flat,
	data_mem_write_ready
);
endmodule

module kv_cache (
	clk,
	reset,
	enable,
	clear_cache,
	append_mode,
	seq_position,
	cache_length,
	key_write_en,
	key_head_sel,
	key_dim_sel,
	key_data_in,
	value_write_en,
	value_head_sel,
	value_dim_sel,
	value_data_in,
	key_read_en,
	key_read_head,
	key_read_pos,
	key_read_dim,
	key_data_out,
	key_valid,
	value_read_en,
	value_read_head,
	value_read_pos,
	value_read_dim,
	value_data_out,
	value_valid,
	batch_read_en,
	batch_head_sel,
	batch_start_pos,
	batch_end_pos,
	batch_valid,
	batch_done,
	sliding_window_en,
	window_size,
	cache_full,
	oldest_position
);
endmodule

module lsu (
	clk,
	reset,
	enable,
	core_state,
	decoded_mem_read_enable,
	decoded_mem_write_enable,
	rs,
	rt,
	mem_read_valid,
	mem_read_address,
	mem_read_ready,
	mem_read_data,
	mem_write_valid,
	mem_write_address,
	mem_write_data,
	mem_write_ready,
	lsu_state,
	lsu_out
);
endmodule

module mem_coalesce (
	clk,
	reset,
	enable,
	req_valid,
	req_address_flat,
	req_is_write,
	req_write_data_flat,
	req_ready,
	req_read_data_flat,
	coalesced_valid,
	coalesced_base_addr,
	coalesced_is_write,
	coalesced_count,
	coalesced_write_data,
	coalesced_ready,
	coalesced_read_data
);
endmodule

module pc (
	clk,
	reset,
	enable,
	core_state,
	decoded_nzp,
	decoded_nzp_write_enable,
	decoded_pc_mux,
	alu_out,
	current_pc,
	next_pc,
	branch_taken,
	instruction
);
endmodule

module registers (
	clk,
	reset,
	enable,
	block_id,
	core_state,
	decoded_rd_address,
	decoded_rs_address,
	decoded_rt_address,
	write_rd_address,
	decoded_reg_write_enable,
	decoded_reg_input_mux,
	decoded_immediate,
	alu_out,
	lsu_out,
	fma_out,
	act_out,
	systolic_out,
	rs,
	rt,
	rd_data
);
endmodule

module scheduler (
	clk,
	reset,
	start,
	decoded_fma_enable,
	decoded_ret,
	decoded_branch,
	branch_taken,
	branch_target,
	reconverge_pc,
	fetcher_state,
	lsu_state_flat,
	current_pc,
	next_pc_flat,
	active_mask,
	diverged,
	core_state,
	done
);
endmodule

module systolic_array (
	clk,
	reset,
	enable,
	clear_acc,
	load_weights,
	compute_enable,
	a_inputs_flat,
	b_inputs_flat,
	results_flat,
	ready
);
endmodule

module systolic_pe (
	clk,
	reset,
	enable,
	clear_acc,
	load_weight,
	compute_enable,
	a_in,
	b_in,
	a_out,
	b_out,
	acc_out
);
endmodule

module weight_mem (
	clk,
	reset,
	enable,
	weight_read_en,
	weight_bank_sel,
	weight_addr,
	weight_data_out,
	weight_valid,
	weight_write_en,
	weight_write_bank,
	weight_write_addr,
	weight_write_data,
	act_read_en,
	act_write_en,
	act_bank_sel,
	act_addr,
	act_data_in,
	act_data_out,
	act_valid,
	swap_buffers,
	prefetch_en,
	prefetch_start_addr,
	prefetch_length,
	prefetch_done,
	bank_busy
);
endmodule

