/* Blackbox stub generated by make_stub.py */

module systolic_pe (
	clk,
	reset,
	enable,
	clear_acc,
	load_weight,
	compute_enable,
	a_in,
	b_in,
	a_out,
	b_out,
	acc_out
);
endmodule

module systolic_array (
	clk,
	reset,
	enable,
	clear_acc,
	load_weights,
	compute_enable,
	a_inputs_flat,
	b_inputs_flat,
	results_flat,
	ready
);
endmodule

