// Auto-generated by LibreLane
module core_tile(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input core_reset,
  input start,
  output done,
  input[7:0] block_id,
  input[3:0] thread_count,
  output program_mem_read_valid,
  output[8:0] program_mem_read_address,
  input program_mem_read_ready,
  input[15:0] program_mem_read_data,
  output data_mem_read_valid,
  output[18:0] data_mem_read_address,
  input data_mem_read_ready,
  input[15:0] data_mem_read_data,
  output data_mem_write_valid,
  output[18:0] data_mem_write_address,
  output[15:0] data_mem_write_data,
  input data_mem_write_ready
);
endmodule
