// Auto-generated by LibreLane
module systolic_pe(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input enable,
  input clear_acc,
  input load_weight,
  input compute_enable,
  input[15:0] a_in,
  input[15:0] b_in,
  output[15:0] a_out,
  output[15:0] b_out,
  output[15:0] acc_out
);
endmodule
