import sys
import re

def make_stub(input_path, output_path):
    with open(input_path, "r") as f:
        content = f.read()

    # Strip single line and block comments
    content_clean = re.sub(r"//.*?\n", "\n", content)
    content_clean = re.sub(r"/\*.*?\*/", "", content_clean, flags=re.DOTALL)

    # Find all module headers ending in semicolon
    # This matches: module name ... ;
    modules = re.findall(r"\bmodule\s+\w+.*?;", content_clean, flags=re.DOTALL)

    with open(output_path, "w") as out:
        out.write("/* Blackbox stub generated by make_stub.py */\n\n")
        for mod in modules:
            out.write(mod + "\n")
            out.write("endmodule\n\n")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python make_stub.py <input.v> <output.v>")
        sys.exit(1)
    make_stub(sys.argv[1], sys.argv[2])
